---
- name: "check deployed"
  include_role:
    name: helm/chart/check
  vars:
    helm_chart_check_namespace: monitoring
    helm_chart_check_name: grafana
  when: (inventory_hostname == groups['kubernetes_masters'][0])

- name: deploy
  include_role:
    name: helm/chart/install
  vars:
    helm_install_namespace: monitoring
    helm_install_name: grafana
    helm_install_chart: "stable/grafana"
    helm_install_wait: yes
    helm_install_set:
      - key: service.type
        value: "LoadBalancer"
      - key: persistence.enabled
        value: "true"
      - key: persistence.storageClassName
        value: "rook-ceph-block"
      - key: persistence.accessModes
        value: "{ReadWriteOnce}"
      - key: persistence.size
        value: "10Gi"
  when: (inventory_hostname == groups['kubernetes_masters'][0])
        and (not helm_chart_check)
