---
- name: check if calico is installed
  shell: "/usr/bin/kubectl --kubeconfig=/etc/kubernetes/admin.conf --namespace=kube-system get pod --no-headers=true --selector k8s-app=calico-kube-controllers | wc -l"
  changed_when: no
  register: calico_kubernetes_installed
  when: inventory_hostname == groups['kubernetes_masters'][0]

- name: install calico
  shell: "/usr/bin/kubectl apply --kubeconfig=/etc/kubernetes/admin.conf -f \"https://docs.projectcalico.org/manifests/calico.yaml\""
  when: (inventory_hostname == groups['kubernetes_masters'][0])
        and (calico_kubernetes_installed.stdout | int == 0)
