---
- name: create temporary directory
  tempfile:
    state: directory
    suffix: metallb
  register: metallb_temp_directory

- name: "create configuration : layer 2"
  template:
    src: layer-2.yaml.j2
    dest: "{{ metallb_temp_directory.path }}/ansible_metallb_configuration.yaml"
  when: metallb_mode == "layer-2"

- name: "create configuration : bgp"
  template:
    src: bgp.yaml.j2
    dest: "{{ metallb_temp_directory.path }}/ansible_metallb_configuration.yaml"
  when: metallb_mode == "bgp"

- name: "deploy : create namespace"
  shell: "/usr/bin/kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f \"https://raw.githubusercontent.com/metallb/metallb/v{{ metallb_version }}/manifests/namespace.yaml\""

- name: "deploy : create configuration"
  shell: "/usr/bin/kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f \"{{ metallb_temp_directory.path }}/ansible_metallb_configuration.yaml\""

- name: "deploy : create deployment"
  shell: "/usr/bin/kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f \"https://raw.githubusercontent.com/metallb/metallb/v{{ metallb_version }}/manifests/metallb.yaml\""

- name: "deploy : create secret"
  shell: "/usr/bin/kubectl --kubeconfig=/etc/kubernetes/admin.conf create secret generic -n metallb-system memberlist --from-literal=secretkey=\"$(openssl rand -base64 128)\""

- name: delete temporary directory
  file:
    state: absent
    path: "{{ metallb_temp_directory.path }}"
