---
- name: "check deployed"
  include_role:
    name: helm/chart/check
  vars:
    helm_chart_check_namespace: metallb
    helm_chart_check_name: metallb
  when: (inventory_hostname == groups['kubernetes_masters'][0])

- include_tasks: deploy.yml
  when: (inventory_hostname == groups['kubernetes_masters'][0])
        and (not helm_chart_check)
