---
- name: install epel-release
  yum:
    name:
      - epel-release
    state: present

- name: install package dependencies
  yum:
    name:
      - python-docker-py
      - python-passlib
      - python-bcrypt
    state: present
