---
- name: "check deployed"
  include_role:
    name: helm/chart/check
  vars:
    helm_chart_check_namespace: rook-ceph
    helm_chart_check_name: rook-ceph
  when: (inventory_hostname == groups['kubernetes_masters'][0])

- name: "deploy"
  include_tasks: deploy.yml
  when: (inventory_hostname == groups['kubernetes_masters'][0])
        and (not helm_chart_check)
